import Link from 'next/link'
import Image from 'next/image'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Box from "@mui/material/Box"
import Typography from "@mui/material/Typography"
import clsx from 'clsx'

import { menuLinks, categoryLinks } from './constants'
import Logo from '../../assets/images/logo.jpg'
import useStyles from "./styles"

const Header = () => {
  const { classes } = useStyles()
  const router = useRouter()

  return(
    <>
      <Head>
        <title>Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={classes.headerRoot}>
        <Box className={classes.navbar}>
          {menuLinks.map(({ name, to }) =>
            <Link
              className={clsx(classes.link, {[classes.activeLink]: router.asPath === to })}
              key={to}
              href={to}
            >
              {name}
            </Link>
          )}
        </Box>
        <Image
          className={classes.logo}
          src={Logo}
          alt='logo'
          priority
        />
        <Box className={classes.categoryContainer}>
          <Box className={classes.categories}>
            {categoryLinks.map(c =>
              <Typography key={c.name}>
                {c.name}
              </Typography>
            )}
          </Box>
        </Box>
      </Box>
    </>
  )
}

export default Header